name: Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Change directory to lab4Projects26099
        run: |
          cd lab4Projects26099

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Python script
        run: |
          python main.py

      - name: Send request to prediction endpoint
        run: |
          curl -X POST -F "file=@cleaned_data.csv" http://localhost:5000/predict
