name: Pobierz dane z Google Sheets

on:
  push:
    branches:
      - Lab2---Obr-bka-danych

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib pandas scikit-learn gspread requests oauth2client faker
          
      - name: Pobierz dane z Google Sheets
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          python3 pobierz_dane.py

      - name: Oczyszczenie danych
        env:  
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          python3 czysc_dane.py

      - name: Upload log.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: log.txt

      - name: Upload report.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: report-file
          path: report.txt

  display_report:
    needs: get_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download report artifact
        uses: actions/download-artifact@v3
        with:
          name: report-file

      - name: Display report content
        run: cat report.txt
