name: Start Flask Application

on:
  push:
    branches:
      - main

jobs:
  start-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r lab4Projects26099/requirements.txt

      - name: Run the Flask application
        run: |
          cd lab4Projects26099
          export FLASK_APP=main.py
          flask run --host=0.0.0.0 --port=5000 & # Uruchomienie aplikacji Flask w tle
          sleep 5  # Czekaj chwilę, aby serwer miał czas na uruchomienie

      - name: Send request to prediction endpoint
        run: |
          for i in {1..5}; do # Spróbuj 5 razy
            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -F "file=@lab4Projects26099/cleaned_data.csv" http://localhost:5000/predict)
            if [ "$response" -eq 200 ]; then
              echo "Received response from server."
              break
            else
              echo "Server not responding, retrying in 5 seconds..."
              sleep 5
            fi
          done
          
      - name: Send request to prediction endpoint and save response
        run: |
          response=$(curl -X POST -F "file=@lab4Projects26099/cleaned_data.csv" http://localhost:5000/predict)
          echo "Response from server:" > response.txt
          echo "$response" >> response.txt  # Zapisz odpowiedź do pliku
          
      - name: Read response from file
        run: |
          echo "Response from server read from file:"
          cat response.txt  # Wyświetlenie odpowiedzi z pliku
