name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Load best_model.pkl
        run: |
          # Zakładając, że artefakt jest z workflow z task3
          mkdir model
          echo "Downloading best_model.pkl"
          curl -L -o model/best_model.pkl https://github.com/PJATK-ASI-2024/Lab3ASIs26099/raw/task3/best_model.pkl
          ls -la model
