name: Start Flask Application

on:
  push:
    branches:
      - main

jobs:
  start-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r lab4Projects26099/requirements.txt

      - name: Install tmux
        run: |
          sudo apt-get update
          sudo apt-get install tmux -y

      - name: Run the Flask application in tmux
        run: |
          cd lab4Projects26099
          export FLASK_APP=main.py
          tmux new-session -d -s flask_session "flask run --host=0.0.0.0 --port=5000" # Uruchomienie aplikacji Flask w nowej sesji tmux
          sleep 5  # Czekaj chwilę, aby serwer miał czas na uruchomienie
          response=$(curl -X POST -F "file=@lab4Projects26099/cleaned_data.csv" http://localhost:5000/predict)
          echo "Response from server:" > response.txt
          echo "$response" >> response.txt  # Zapisz odpowiedź do pliku

          
      - name: Read response from file
        run: |
          echo "Response from server read from file:"
          cat response.txt  # Wyświetlenie odpowiedzi z pliku
