name: Start Flask Application

on:
  push:
    branches:
      - main

jobs:
  start-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r lab4Projects26099/requirements.txt

      - name: Run the Python script
        run: |
          cd lab4Projects26099
          nohup python main.py & # Uruchomienie aplikacji w tle

      - name: Send request to prediction endpoint
        run: |
          for i in {1..5}; do # Spróbuj 5 razy
            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -F "file=@lab4Projects26099/cleaned_data.csv" http://localhost:5000/predict)
            if [ "$response" -eq 200 ]; then
              echo "Received response from server."
              break
            else
              echo "Server not responding, retrying in 5 seconds..."
              sleep 5
            fi
          done
          
      - name: Send request to prediction endpoint
        run: |
          curl -X POST -F "file=@lab4Projects26099/cleaned_data.csv" http://localhost:5000/predict
