name: Run Python Scripts and Save Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

        run: |
          python -m pip install --upgrade pip
          pip install joblib pandas numpy matplotlib seaborn scikit-learn python-docx pdfkit
          
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf || exit 0  # Avoid stopping if this fails

      - name: Run czyszczenie_porównywanieModeli.py
        run: |
          python asi3Project/czyszczenie_porównywanieModeli.py

      - name: Run trening_i_raport.py
        run: |
          python asi3Project/trening_i_raport.py

      - name: List files in asi3Project
        run: |
          ls -la asi3Project  # This will help verify if .docx files are present

      - name: Upload .docx artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docx-files
          path: /home/runner/work/Lab3ASIs26099/Lab3ASIs26099/*.docx
