name: Pobierz dane z Google Sheets

on:
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Clone Lab3-Analizator_wynikow repo
        env:
          ac: ${{ secrets.ACCESSTOKEN }}  # GitHub PAT stored in secrets
        run: |
          git clone https://$ac@github.com/PJATK-ASI-2024/Lab3-Analizator_wynikow.git
          cd Lab3-Analizator_wynikow

      - name: Run Python script in Lab3ASIs26099/asi3Project
        run: |
          python asi3Project/main.py
